### ISSUE TITLE
Example of initialization of a nested struct 

### ISSUE THREAD

**Issue by rc979** [e-XpertSolutions/f5-rest-client#10]
Hello!

Do you have an example of initializing a nested struct such as the [Pools field on the Wideip struct](https://github.com/e-XpertSolutions/f5-rest-client/blob/master/f5/gtm/wideip_a.go#L33)? I've tried various different ways and I'm unable to make it work. Is there a reason why you wouldn't make this field use one of your custom types instead of a slice of structs? 

Thank you and keep up the great work!

**Comment by rc979** [comment]
Hi! Any chance you can help me out with this one? :-) Thanks!

**Comment by gilliek** [comment]
Hi @rc979,

Sorry for my late reply.

The reason why it is a nested struct is that this part of the code has been generated automatically and the generator only creates nested structures. But it would probably be better to use a custom type instead :-)

For now, here is the way to initialize a nested list of structs:

```
foo := gtm.Wideip{
   Pools: []struct{
		Name  string `json:"name,omitempty"`
		NameReference struct {
			Link string `json:"link,omitempty"`
		} `json:"nameReference,omitempty"`
		Order     int    `json:"order,omitempty"`
		Partition string `json:"partition,omitempty"`
		Ratio     int    `json:"ratio,omitempty"`
	}{
            {
                 Name: "some-name",
                 Order: 1,
                 Partition: "Common",
            },
       },
}
```

Basically it is an anonymous struct and as such must be re-declared in the exact same way as the one from gtm.Wideip, including the json annotations.

Why do you need to initialize this list manually btw? It is returned by the iControl REST API on GET requests but you AFAIK you cannot use it for creation and update.

**Comment by rc979** [comment]
Thanks! I wanted to use it for creation and update, if you can’t use this
for these purposes how should you do it?

**Comment by gilliek** [comment]
I would need to do some tests to answer your question. I'll test this in our lab and I'll get back to you ;-)

**Comment by gilliek** [comment]
So, I made some tests and I was wrong. You can use the **Pools** field to provide _existing pool_ objects in order to link the Wideip object to the pools during creation and update, as you wanted to use it.

Note that the Pools must already exist or need to be _created beforehand_. They won't be created on the fly.
