### ISSUE TITLE
UploadFile fail to upload BIGIP iso image

### ISSUE THREAD

**Issue by vincentmli** [e-XpertSolutions/f5-rest-client#11]
I have a sample code using the UploadFile to upload BIGIP ISO image, it always failed at  sending  534249472 bytes. I used python script to upload BIGIP ISO image and it works, does not seem to be BIGIP issue.

sample code below:
<pre>
package main

import (
        "flag"
        "fmt"
        "github.com/e-XpertSolutions/f5-rest-client/f5"
        "log"
        "os"
        "path/filepath"
)

func main() {
        // give an ip at command line
        ip := flag.String("ip", "127.0.0.1", "BIGIP mgmt ip")
        user := flag.String("user", "admin", "BIGIP login user")
        password := flag.String("password", "admin", "BIGIP login password")
        iso := flag.String("iso", "/home/vincent/BIGIP-13.0.0.0.0.1645.iso", "iso file to upload")
        flag.Parse()

        // setup F5 BigIP client
        f5Client, err := f5.NewBasicClient("https://"+*ip, *user, *password)
        if err != nil {
                log.Fatal(err)
        }
        f5Client.DisableCertCheck()

        info, err := os.Stat(*iso)
        log.Println("iso size %d", info.Size())
        if err != nil {
                fmt.Errorf("failed to gather information about '%s': %v", *iso, err)
        }
        f, err := os.Open(*iso)
        if err != nil {
                fmt.Errorf("failed to read file from path: %v", err)
        }
        defer f.Close()

        if _, err = f5Client.UploadFile(f, filepath.Base(*iso), info.Size()); err != nil {
                fmt.Errorf("failed to upload image file: %v", err)
        }

}

</pre>

I need to make a one-line change in upload.go to use the PathUploadImage "/mgmt/cm/autodeploy/software-image-uploads"

<pre>
diff --git a/f5/upload.go b/f5/upload.go
index 0e8c32e..f104770 100644
--- a/f5/upload.go
+++ b/f5/upload.go
@@ -48,7 +48,7 @@ func (c *Client) UploadFile(r io.Reader, filename string, filesize int64) (*Uplo
                        chunk = remainingBytes
                }

-               req, err := c.MakeUploadRequest(PathUploadFile+"/"+filename, io.LimitReader(r, chunk), bytesSent, chunk, filesize)
+               req, err := c.MakeUploadRequest(PathUploadImage+"/"+filename, io.LimitReader(r, chunk), bytesSent, chunk, filesize)
                if err != nil {
                        return nil, err
                }
</pre>

**Comment by vincentmli** [comment]
I git pulled the most recent commit and problem still occurs:

<pre>
package main

import (
        "flag"
        "fmt"
        "github.com/e-XpertSolutions/f5-rest-client/f5"
        "log"
        "os"
        "path/filepath"
)

func main() {
        // give an ip at command line
        ip := flag.String("ip", "127.0.0.1", "BIGIP mgmt ip")
        user := flag.String("user", "admin", "BIGIP login user")
        password := flag.String("password", "admin", "BIGIP login password")
        iso := flag.String("iso", "/home/vincent/BIGIP-13.0.0.0.0.1645.iso", "iso file to upload")
        flag.Parse()

        // setup F5 BigIP client
        f5Client, err := f5.NewBasicClient("https://"+*ip, *user, *password)
        if err != nil {
                log.Fatal(err)
        }
        f5Client.DisableCertCheck()

        info, err := os.Stat(*iso)
        log.Println("iso size %d", info.Size())
        if err != nil {
                fmt.Errorf("failed to gather information about '%s': %v", *iso, err)
        }
        f, err := os.Open(*iso)
        if err != nil {
                fmt.Errorf("failed to read file from path: %v", err)
        }
        defer f.Close()

        if _, err = f5Client.UploadImage(f, filepath.Base(*iso), info.Size()); err != nil {
                fmt.Errorf("failed to upload image file: %v", err)
        }

}
</pre>

**Comment by gilliek** [comment]
Hi @vincentmli and thank you for reporting the issue.

I managed to reproduce and fix the problem. If you still encounter issues with the upload, feel free to re-open an issue and, please, add the error message and the BigIP version in the description :wink: 

Best,

Kevin

**Comment by vincentmli** [comment]
thank you for the quick fix! it works, will report the BIGIP version next time :+1:
