### ISSUE TITLE
Allow use of custom http.Client

### ISSUE THREAD

**Issue by dvorakd** [e-XpertSolutions/f5-rest-client#12]
Would it be possible to allow a way for a user to pass as a parameter their own `http.Client` or `http.RoundTripper` when creating the `Client` with `NewBasicClient` or `NewTokenClient`? 

See https://github.com/e-XpertSolutions/f5-rest-client/blob/master/f5/client.go

Example use cases include adding the ability to add in log functions to log requests and responses or to be able to customize  #`TLSClientConfig`.

**Comment by gilliek** [comment]
I like the idea of letting the user use his own `http.Client` but I find that adding another extra argument for each "constructor" would be cumbersome, especially that in most cases the default `http.Client` is good enough.

What about creating a setter to replace the underlying `http.Client`? Something lile `SetHTTPClient(c *http.Client)`?

**Comment by dvorakd** [comment]
Agreed.  Leave the function definitions as is, if possible.  Using a `SetHTTPClient` when starting with `NewBasicClient` or `TokenClientConnection` should work fine.  The function `NewTokenClient` may need changes since it makes a request from within it.
