### ISSUE TITLE
Bumping version number

### ISSUE THREAD

**Issue by Veilyon** [e-XpertSolutions/f5-rest-client#17]
Hi,

Would it be possible to release a new version (i.e. add a new tag, `v0.1.0`, for example)?
Both `dep` and `go mod` depend on such tags to manage dependencies.

The latest release of this repo seems to be `v0.0.0` from two years ago, meaning that this library can't currently be used without checking out the repo each time you wan't to use it.

Thanks.

**Comment by gilliek** [comment]
Hi,

Thank you for reporting this issue and sorry for the delayed answer :)
I tagged the v0.1.0.


Best,
