### ISSUE TITLE
Code update problem

### ISSUE THREAD

**Issue by zhangfengsd** [e-XpertSolutions/f5-rest-client#25]
I use f5-rest-Client through Gomod, but the code I pull is not what I submit(https://github.com/e-XpertSolutions/f5-rest-client/blob/master/f5/ltm/pool_stats.go)

my go.mod is:

go 1.14

require (
	github.com/e-XpertSolutions/f5-rest-client v0.1.0
	github.com/gogf/gf v1.13.4
	github.com/hpifu/go-kit v1.8.7
)

**Comment by gilliek** [comment]
Yes indeed, we did not create a Git tag after the latest change. I can do this tomorrow.

You can also get the latest version that includes your PR by issuing:

```
go get -u github.com/e-XpertSolutions/f5-rest-client@master
````

It will update your `go.mod` with the dependency pointing to the latest commit of the master branch.

**Comment by zhangfengsd** [comment]
Thank you. I got the latest version via `go get-u github.com/e-XpertSolutions/f5-rest-client@master`.

**Comment by zhangfengsd** [comment]
Thank you. I got the latest version via `go get-u github.com/e-XpertSolutions/f5-rest-client@master.`
