### ISSUE TITLE
certificate signed by unknown authority

### ISSUE THREAD

**Issue by yangmingbai** [e-XpertSolutions/f5-rest-client#27]
when i  connected  f5 address using my username and password, i got an error,but my address ,username,password  are all right
'f5Client check err authentication verification failed: Get "https://172.31.41.50:10443/mgmt/tm": x509: certificate signed by unknown authority' 

```go
url := "https://172.31.41.50:10443"  
f5Client, err := f5.NewBasicClient(url, "username", " password")  
if err != nil{  
	fmt.Println("f5Client err",err.Error())  
}  
checkerr := f5Client.CheckAuth()  
if checkerr != nil{  
	fmt.Println("f5Client check err",checkerr.Error())  
}  
```

**Comment by gilliek** [comment]
The certificate on your management is probably a self signed.You need to use the [DisableCertCheck()](https://pkg.go.dev/github.com/e-XpertSolutions/f5-rest-client/f5#Client.DisableCertCheck) method:

url := "https://172.31.41.50:10443"  
f5Client, err := f5.NewBasicClient(url, "username", " password")  
if err != nil{  
	fmt.Println("f5Client err",err.Error())  
}
f5Client.DisableCertCheck()

checkerr := f5Client.CheckAuth()  
if checkerr != nil{  
	fmt.Println("f5Client check err",checkerr.Error())  
}

**Comment by yangmingbai** [comment]
thanks!
