### ISSUE TITLE
support for version 13.

### ISSUE THREAD

**Issue by lanox** [e-XpertSolutions/f5-rest-client#3]
Hi, 
Would you be supporting this for version 13, as it seems like in version 12/13 icrd has been removed.

`2017/11/01 16:10:13 &{[{} {} {}] tm:gtm:pool:a:acollectionstate https://localhost/mgmt/tm/gtm/pool/a?ver=13.0.0}`

that is output I get from do `tmPool.PoolA().ListAll()`

thanks.

**Comment by ydesmarest** [comment]
Hi,
The GTM parts was not developed yet. 

I have done an initial commit to manage GTM components.

Let me know if there are any issues.

Best Regards

**Comment by lanox** [comment]
hi @ydesmarest  oh thanks.
I though by this documentation https://godoc.org/github.com/e-XpertSolutions/f5-rest-client/f5/gtm that gtm was part of the package already ?

**Comment by ydesmarest** [comment]
Hi @lanox 
I just added the pool stats function. You now have :
- Single pool stats: func (pr *PoolAResource) ShowAStats(id string) (*PoolStatsList, error)
- All pool stats: func (pr *PoolAResource) ShowAllAStats() (*PoolStatsList, error)

Stats are given by pool type: A, AAAA, CNAME, MX, NAPTR, SRV

**Comment by lanox** [comment]
Thanks, this is perfect 👍 ...

**Comment by lanox** [comment]
one more question, I couldn't see a way to invalidate the token ? is that possible.

**Comment by gilliek** [comment]
[Now](https://github.com/e-XpertSolutions/f5-rest-client/commit/10f17ad29df1475808a16cc1ff334342af1bd408) you can with [RevokeToken()](https://godoc.org/github.com/e-XpertSolutions/f5-rest-client/f5#Client.RevokeToken)
