### ISSUE TITLE
How to get the snat member list in ltm?

### ISSUE THREAD

**Issue by lefeck** [e-XpertSolutions/f5-rest-client#38]
hi, @gilliek
I want to get the snat member list attribute in ltm, what should I do? We don't see the corresponding method of struct?

**Comment by gilliek** [comment]
Hi @lefeck 

Snat API are not implemented in our client at the moment. To work around the issue you can use the following method:

https://pkg.go.dev/github.com/e-XpertSolutions/f5-rest-client/f5#Client.ReadQuery

```
package main

import (
	"encoding/json"
	"fmt"
	"log"

	"github.com/e-XpertSolutions/f5-rest-client/f5"
)

func main() {
	f5Client, err := f5.NewBasicClient("https://<some-ip-address>", "admin", "admin")
	if err != nil {
		log.Fatal(err)
	}
	f5Client.DisableCertCheck()

        var data struct{
              Items []struct{
                  Name string `json:"name"`
              } `json:"items"`
        }
	if err := f5.ReadQuery("/mgmt/tm/ltm/snatpool", &data); err != nil {
              log.Fatal(err)
        }
}
```

Basically you just need to define the structure returned by the API and use the `ReadQuery` method. 

If you need more attributes, you can also query the API using Postman, cURL or directly from the browser and use somehting like `json-to-go` to generate the Go struct for you:

https://mholt.github.io/json-to-go/

**Comment by lefeck** [comment]
Thanks for the tip, I learned.
