### ISSUE TITLE
cannot use []ltm.Profile literal (type []ltm.Profile) as type []string in field value

### ISSUE THREAD

**Issue by vincentmli** [e-XpertSolutions/f5-rest-client#8]
Sample script:
<pre>

        // Create a Virtual Server
        log.Print("Create a Virtual Server")

        vsConfig := ltm.VirtualServer{
                Name:        "vs_http_" + tx.TransactionID(),
                Destination: "10.1.20.130:80",
                IPProtocol:  "tcp",
                Pool:        "pool_" + tx.TransactionID(),
                SourceAddressTranslation: ltm.SourceAddressTranslation{
                        Type: "automap",
                },
                Profiles: []ltm.Profile{ //<=====HERE struct type Profile
                        {
                                Name:    "tcp-mobile-optimized",
                                Context: "all",
                        },
                        {
                                Name: "http",
                        },
                },
        }

        if err := ltmClient.Virtual().Create(vsConfig); err != nil {
                log.Fatal(err)
        }
</pre>

I think Profiles in VirtualServer struct should be []Profile, not []string

<pre>

diff --git a/f5/ltm/virtual.go b/f5/ltm/virtual.go
index 623088b..4c19f97 100644
--- a/f5/ltm/virtual.go
+++ b/f5/ltm/virtual.go
@@ -52,8 +52,8 @@ type VirtualServer struct {
                IsSubcollection bool   `json:"isSubcollection,omitempty"`
                Link            string `json:"link,omitempty"`
        } `json:"policiesReference,omitempty"`
-       Pool              string   `json:"pool,omitempty"`
-       Profiles          []string `json:"profiles,omitempty"` // only used to link existing profiles a creation or update
+       Pool              string    `json:"pool,omitempty"`
+       Profiles          []Profile `json:"profiles,omitempty"` // only used to link existing profiles a creation or update

</pre>

**Comment by gilliek** [comment]
Hi @vincentmli,

Thank you for reporting this issue. The example from [DevCentral](https://devcentral.f5.com/codeshare/go-library-to-manage-big-ip-icontrol-rest-api-925) is not up to date. We switched from a slice of Profile types to a simple slice of strings because this is how the iControl REST API handles the list of profiles.

I will see with @ydesmarest to update the article on DevCentral.

**Comment by gilliek** [comment]
@vincentmli Yann updated the example on DevCentral.
