### ISSUE TITLE
Question about id parameter

### ISSUE THREAD

**Issue by rc979** [e-XpertSolutions/f5-rest-client#9]
Hi,

Congrats for this amazing package!

For methods that require an "id" parameter for identifying the particular configuration object (such as get or modify), does your package provide a mechanism for obtaining it programmatically? I was able to deduce that the format of this parameter should be "\~partitionName\~objectName" but I am wondering whether your package provides a better way than assemblying this by hand. I also suggest that you document this somewhere :-) 
Thanks!

**Comment by gilliek** [comment]
Hi @rc979,

Thank you very much for your feedback :-)

For now there is unfortunately no mechanism for obtaining it programmatically, but it is planned to add it very soon and probably through a custom type.

I also agree with your suggestion of mentionning it in the documention :+1:

**Comment by gilliek** [comment]
An issue has been created for this implementation of this type and has been integrated in the roadmap for the v1.0.0, in order not to break current implementations.

See #19 for more details
